### ISSUE TITLE
group_vars/webservers

### ISSUE THREAD

**Issue by dimthe** [mikegleasonjr/ansible-role-firewall#12]
Hi 
i need some clarification with this. This path does not exist so i guess i have to create a folder called group_vars and inside that folder create the webservers yaml like in your example :+1: 

in group_vars/webservers.yml you would open up port 80:

firewall_v4_group_rules:
  400 allow web traffic:
    - -A INPUT -p tcp --dport http -j ACCEPT

problem is when i run the play i get this error

ERROR! playbooks must be a list of plays and it complains about this line : 
  firewall_v4_default_rules:
  ^ here

**Comment by mikegleasonjr** [comment]
As discussed via emails, this is an issue with your lack of knowledge regarding Ansible. I was cooperative and redirected you to everything you needed to know to get started.

Asking me a third time, with so short time between the requests, makes me believe you do not want to learn Ansible on your own and are asking others to write your organisation roles on your behalf. Especially that in those emails, your "question" was not really a question but an explanation of your needs and a request to give you the final solution.

Please take some kind of responsibilities as a developer.

Your behaviour is disrespectful and selfish.

**Comment by mikegleasonjr** [comment]
When somebody can't do it for you, you ask another somebody I guess: https://github.com/geerlingguy/ansible-role-firewall/issues/23
