### ISSUE TITLE
Handlers?

### ISSUE THREAD

**Issue by clwells** [mikegleasonjr/ansible-role-firewall#13]
Is anyone else interested in simple handlers?  I've added some in our role here: 

https://github.com/nexcess/ansible-role-firewall/blob/master/handlers/main.yml

And can PR if it's something that's wanted in general.

**Comment by mikegleasonjr** [comment]
I don't think they would work on every platform/versions supoorted.

**Comment by clwells** [comment]
Good point - will refactor and PR if this is something folks want.

**Comment by mikegleasonjr** [comment]
Stale, closing. Feel free to re-open.
