### ISSUE TITLE
Issue with group_vars/webservers.yml example

### ISSUE THREAD

**Issue by egroeg** [mikegleasonjr/ansible-role-firewall#14]
Hi,

Testing this out and I'm trying to get the example below working.  The rules in all.yml are picked up fine, but the rules in webservers.yml are not.  

/etc/ansible/inventory/hosts:

    [webservers]
    example.machine

/etc/ansible/playbooks/fw.ywl:

    - hosts: all
      roles:
        - mikegleasonjr.firewall

/etc/ansible/inventory/group_vars/all.yml:

    firewall_v4_default_rules:
      001 default policies:
        - -P INPUT ACCEPT
        - -P OUTPUT ACCEPT
        - -P FORWARD DROP
      002 allow loopback:
        - -A INPUT -i lo -j ACCEPT
      003 allow ping replies:
        - -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
        - -A OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT
      100 allow established related:
        - -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
      200 allow ssh limiting brute force:
        - -I INPUT -p tcp -d {{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }} --dport     22 -m state --state NEW -m recent --set
        - -I INPUT -p tcp -d {{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }} --dport     22 -m state --state NEW -m recent --update --seconds 60 --hitcount 4 -j DROP
      999 drop everything:
    - -P INPUT DROP

/etc/ansible/inventory/group_vars/webservers.yml:

    ---
    firewall_v4_group_rules:
      005 allow http traffic:
        - -A INPUT -p tcp --dport 80 -j ACCEPT
        - -A INPUT -p tcp --dport 443 -j ACCEPT

I'm running Ansible like so:

    #ansible-playbook -i /etc/ansible/inventory/hosts /etc/ansible/playbooks/fw.ywl -vvv

I've went over the webservers.yml file multiple times and the spacing seems ok and there are no typos that I can see.   

    TASK: [mikegleasonjr.firewall | Load v4 rules] ********************************
    skipping: [example.machine]

As a test, I created another playbook file /etc/ansible/inventory/group_vars/mailservers.yml

    ---
    firewall_v4_group_rules:
      1100 allow mail traffic:
        - -A INPUT -p tcp --dport 25 -j ACCEPT
        - -A INPUT -p tcp --dport 587  -j ACCEPT
        - -A INPUT -p tcp --dport 465  -j ACCEPT
        - -A INPUT -p tcp --dport 110  -j ACCEPT
        - -A INPUT -p tcp --dport 143  -j ACCEPT
        - -A INPUT -p tcp --dport 993  -j ACCEPT
        - -A INPUT -p tcp --dport 995  -j ACCEPT

And this one works? What could be wrong?  What's the best way to get a better picture as to why the rules for the webservers group are being skipped?

**Comment by egroeg** [comment]
Here's what's shown while grabbing the v4_script_load_result register variable with the debug module.  This is a second run after applying the all and mailservers group rules, and the webservers rules being skipped (after deleting /etc/iptables/* and /etc/iptables.v4.generated on the target).  Still not revealing its secrets.

#/etc/ansible/inventory/group_vars# ansible-playbook -i /etc/ansible/inventory/hosts /etc/ansible/playbooks/fw.ywl -vvvvvvv
 
  PLAY [all] ********************************************************************
 
  GATHERING FACTS ***************************************************************
  <example.machine> ESTABLISH CONNECTION FOR USER: root
  <example.machine> REMOTE_MODULE setup
  <example.machine> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-wit
    <example.machine> PUT /tmp/tmpmAu7Gy TO /root/.ansible/tmp/ansible-tmp-1484064424.31-208025214391664/setup
 <example.machine> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-wit
 11 ok: [example.machine]

 TASK: [mikegleasonjr.firewall | Generate v4 rules] ****************************
 <example.machine> ESTABLISH CONNECTION FOR USER: root
 <example.machine> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-wit
 <example.machine> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-wit
 <example.machine> PUT /tmp/tmpxf0PZS TO /root/.ansible/tmp/ansible-tmp-1484064425.72-232849379225842/file
 <example.machine> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-wit
 ok: [example.machine] => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/etc/iptables.v4.generated", "size": 1620, "state": "file", "uid": 0}

 TASK: [mikegleasonjr.firewall | Load v4 rules] ********************************
 skipping: [example.machine]

 TASK: [mikegleasonjr.firewall | Generate v6 rules] ****************************
 skipping: [example.machine]
 
 TASK: [mikegleasonjr.firewall | Load v6 rules] ********************************
 skipping: [example.machine]

 TASK: [mikegleasonjr.firewall | Debug v4_script_load_result] ******************
 <example.machine> ESTABLISH CONNECTION FOR USER: root
 ok: [example.machine] => {
     "v4_script_load_result": {
          "changed": false,
          "skipped": true
      }
 }
 
 TASK: [mikegleasonjr.firewall | Debug v4_script_load_result.stdout as part of a string] ***
 <example.machine> ESTABLISH CONNECTION FOR USER: root
 fatal: [example.machine] => One or more undefined variables: 'dict object' has no attribute 'stdout'
 
 FATAL: all hosts have already failed -- aborting
 
 PLAY RECAP ********************************************************************
to retry, use: --limit @/root/fw.ywl.retry

**Comment by egroeg** [comment]
I just discovered that if I list the target in only the webservers group in the hosts inventory file, it works.  It seems that if I have a hostname in multiple groups, e.g.,

    [webservers]
    example.machine
    [mailservers]
    example.machines

Only one group gets its rules applied (on top of the "all" rules).  Am I doing something wrong?

**Comment by egroeg** [comment]
After looking over this more closely it appears that when a machine is in more than one group, only one set of rules is applied.  In the example above, I had example machine in [all], [mailservers] and [webservers] in the hosts inventory file.  Only the all.yml and mailservers.yml rules are being applied.  If I remove the host from mailservers, the webservers rules are applied.  I cannot have more than 2 listings of a host in a group w/o those rules getting skipped.

**Comment by davidmnoriega** [comment]
I think you need the following added to your `ansible.cfg`:
```ini
[defaults]
hash_behaviour = merge
```

**Comment by egroeg** [comment]
Thank you, David.  That was it.

**Comment by mikegleasonjr** [comment]
Thanks @davidmnoriega, sorry @egroeg rather busy at the moment! Thanks both for using the role.
