### ISSUE TITLE
Which BSD-License exactly?

### ISSUE THREAD

**Issue by markgraf** [mikegleasonjr/ansible-role-firewall#18]
Would you be so kind an give more detail as to which BSD-License you are using?

There are three versions I think:
- Original / 4-clause
- Modified / 3-clause
- Simplified / 2-clause

Modified and simple would be compatible with GPL, while the original version is not. Simplified would be compatible with commercial licenses.

Thanks in advance!

**Comment by mikegleasonjr** [comment]
Added Simplified license for more flexibility for everyone. Thanks!
