### ISSUE TITLE
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated.

### ISSUE THREAD

**Issue by gerhard-tinned** [mikegleasonjr/ansible-role-firewall#27]
Since 2.4, "include" statement is marked as  deprecated. It can be easy fixed by just changing it to "include_tasks" which will only include the file when the condition matches.

For completness, here the complete warning generated by ansible 2.4.2.0.

> [DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
> [DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

The file "tasks/main.yml" would therefore look like this.

```
- include_tasks: rules.yml

- include_tasks: persist-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: persist-redhat.yml
when: ansible_os_family == 'RedHat'

```

I guess its not worth creating a fork and a pull request for this, isn't it?

**Comment by mikegleasonjr** [comment]
Yup don't bother I will do it this week! Thank you for the code!

**Comment by gerhard-tinned** [comment]
Thanks that sounds awesome. :)

**Comment by mikegleasonjr** [comment]
Sorry for the delay, better late than never 🙏
