### ISSUE TITLE
Fails when used on a system without 'nat' or any other default table

### ISSUE THREAD

**Issue by wojciech-kopras** [mikegleasonjr/ansible-role-firewall#29]
On a server I am not allowed to have "nat" table. And unfortunately on that system I cannot use this role, because those initial commands from "templates/generated.v4.j2" cause failures.

Probably for users like me it would be useful to change this initial cleanup commands from:
```
iptables -t raw -F
iptables -t raw -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
```
to:
```
iptables -t raw -F >/dev/null 2>&1 || true
iptables -t raw -X >/dev/null 2>&1 || true
iptables -t nat -F >/dev/null 2>&1 || true
iptables -t nat -X >/dev/null 2>&1 || true
iptables -t mangle -F >/dev/null 2>&1 || true
iptables -t mangle -X >/dev/null 2>&1 || true
```
Because failures on them are not interesting for admin - I know that I don't have those tables - because I didn't configured using them. But it's good to keep those cleanup commands, so that if any of those tables is present, it gets cleaned up by default.

The same for ip6tables.

Of course I can use a modified copy of this role, but it would be great to have it working by default.

**Comment by mikegleasonjr** [comment]
I will make the default cleanup rules configurable! You are not the first getting a problem with this.
