### ISSUE TITLE
Should use iptables-persistent

### ISSUE THREAD

**Issue by lightraven24** [mikegleasonjr/ansible-role-firewall#3]
This role should leverage the functionality available in the {iptables,netfilter}-persistent packages on Debian-based systems.

**Comment by conorsch** [comment]
@lightraven24 Can you elaborate on why the role should leverage those packages? What functionality do those packages provide that the role doesn't already handle?

**Comment by mikegleasonjr** [comment]
Will close this one, if it ain't broke...

**Comment by lightraven24** [comment]
It has more to do with the fact that you should be using the functionality and tools built into the system (with all the init scripts, etc), rather than creating them yourselves. With for example, what's in templates, restore.v4.j2 and save.v4.j2.

**Comment by lightraven24** [comment]
Also, looking at the package scripts - it'll give you an easy way to support ip6tables too.

**Comment by mikegleasonjr** [comment]
As soon as I get out of the Sahara desert, I'll look into using the {iptables,netfilter}-persistent packages for Debian.

Originally, this was laid out like that to support RedHat which didn't have those.

**Comment by raarts** [comment]
On redhat you might want to look at `/etc/sysconfig/iptables` for persistency support.

**Comment by mikegleasonjr** [comment]
Would gladly look at PRs

**Comment by conorsch** [comment]
@lightraven24 @raarts Not disagreeing with the motivation here, but some more detailed examples would be very helpful. I use this role mostly on Debian-based systems, and am quite pleased with the role's functionality (particularly the composability between default, group, and host vars). Would gladly review changes that are more consistent with OS standards, but the role as written matches how I've typically scripted iptables rules for years.

**Comment by raarts** [comment]
So how do you restart the firewall on your systems? Because the 'official' way would be service firewall restart, and that will not work with the current rule setup I think.

**Comment by mikegleasonjr** [comment]
OK now we have a use case where it would make sense to use the official tools. Because before no one really expressed how it would be beneficial to use them over the current setup.

I did it this way to have a single code base for basic iptables rules reloading on startup.

Will look into it.

**Comment by mikegleasonjr** [comment]
I updated the role to use `{iptables,netfilter}-persistent` on Debian. Feel free to re-open if there is anything missing.

I tagged the role 1.0.0 because now we are only using system tools on all platforms.

Thank you for your suggestions...
