### ISSUE TITLE
Possible to auto-add firewall rules when a dependent roles is included?

### ISSUE THREAD

**Issue by raarts** [mikegleasonjr/ansible-role-firewall#4]
Currently I'm using global rule definitions in group_vars and host_vars, but would it be possible to add iptables rules when adding a dependent role, and specifying the rules inside the directory for that role?

**Comment by mikegleasonjr** [comment]
Can you give me an example with the dependency tree of what your are trying to do?

**Comment by conorsch** [comment]
> would it be possible to add iptables rules when adding a dependent role

@raarts What you describe is absolutely possible: set `mikegleasonjr.firewall` as a dependency in `meta/main.yml`, then specify your custom firewall rules in `vars/main.yml`. Note that you cannot use `defaults/main.yml` to override the firewall rules—that behavior changed in Ansible v2, IIRC.

If you provide more info about the services you're trying to configure, I'd be happy to put together a more explicit example of directory structure and variable overrides.

**Comment by mikegleasonjr** [comment]
Thanks for jumping in @conorsch!

**Comment by mikegleasonjr** [comment]
Since we haven't heard anything after a month I will assume OP found a solution!

**Comment by raarts** [comment]
I'm sorry, got distracted, but yes. @conosch 's solution works for me. Thanks!
