### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by mikegleasonjr** [mikegleasonjr/ansible-role-firewall#8]
Anyone have a good set of rules that would correspond to the [IPv4 ones](https://github.com/mikegleasonjr/ansible-role-firewall/blob/master/defaults/main.yml#L2)?

**Comment by maloddon** [comment]
I can work on some, maybe.

In fact, there's no major changes, maybe just with icmpv6 types.

**Comment by mikegleasonjr** [comment]
@maloddon Thanks, I'm a complete noob regarding IPv6. I can do the modifications to the role, I just need a set of default ipv6 rules 😄

**Comment by mikegleasonjr** [comment]
Fixed with 175aad8

Thanks @maloddon
